-- Add is_npc flag to characters table to clearly identify AI-generated NPCs
ALTER TABLE public.characters 
ADD COLUMN IF NOT EXISTS is_npc BOOLEAN NOT NULL DEFAULT false;

-- Add an index for efficient filtering
CREATE INDEX IF NOT EXISTS idx_characters_is_npc ON public.characters(is_npc);

-- Update existing hidden AI characters to be marked as NPCs
-- Characters that are both hidden AND private are likely AI NPCs
UPDATE public.characters 
SET is_npc = true 
WHERE is_hidden = true AND is_private = true;

-- Add a comment for documentation
COMMENT ON COLUMN public.characters.is_npc IS 'True if this character was auto-generated by the AI system and should not appear in user profiles';